version: '3.7'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  web:
    build: .
    command: npm run serve_reseed
#    volumes:
#      - .:/usr/src/app
    ports:
      - 80:80
    depends_on:
      - mongo
    environment:
      - STATUS=ok
      - MONGODB_URI=mongodb://mongo:27017/
      - NODE_PORT=80
      - PUPPETEER_HEADLESS=true

volumes:
  mongodb_data_container:
