import AbstractProducer from '../../../abstract_producer';
import { IPublicRecordProducer } from '../../../../../../models/public_record_producer';

import puppeteer from 'puppeteer';
import db from '../../../../../../models/db';

const docTypeObjs: any = {
    "ASGMT": [
      "AMEND MORTGAGE",
      "ASGMT",
      "ASGMT & AGRMT",
      "ASGMT & APPMT T",
      "ASGMT & ASSUMP",
      "ASGMT & CONSENT",
      "ASGMT CONTRACT",
      "ASGMT JDGMT",
      "ASGMT LEASE",
      "ASGMT OPTION",
      "ASGMT PTNRSHP",
      "ASGMT SUBLEASE",
      "ASGMT/ALLOCATIO",
      "ASGMT/AMEND",
      "ASGMT/APMT SUB ",
      "ASGMT/ASSUM/REL",
      "ASGMT/SUBORD/AG",
      "ASGMT/TERM AGRM",
      "ASGMT/TERM LEAS",
      "CONFIRM ASGMT",
      "CONSENT ASGMT",
      "CONTRACT ASGMT",
      "COR ASGMT",
      "CORR ASGMT AGRM",
      "CORR ASGMT LEAS",
      "CORR LEASE ASGM",
      "DISCHARGE ASGMT",
      "DUPLICATE ASGMT",
      "LEASE ASGMT",
      "LEASE ASGMT/AGR",
      "MEMO ASGMT",
      "MOD ASGMT",
      "MOD/AMEND ASGMT",
      "MODIFY & ASGMT",
      "NOTICE ASGMT",
      "OPTION ASGMT",
      "REPLACE ASGMT",
      "RW ASGMT",
      "SUBORD ASGMT",
      "SUP ASGMT",
      "VOID ASGMT",
      "VOID CAN ASGMT"
    ],
    "CORPORATION": [
      "AGRMT ASSUMED",
      "AGRMT/ASSUME NA",
      "AMEND",
      "AMEND",
      "AMEND 1ST REFUS",
      "AMEND ASSUMED",
      "AMEND AUTHORITY",
      "AMEND BY LAWS",
      "AMEND CERT",
      "AMEND CERT AUTH",
      "AMEND CHARTER",
      "AMEND CORPORATI",
      "AMEND INCORP",
      "AMEND N/C RO & ",
      "AMEND NC",
      "AMEND PTNRSHP",
      "AMEND R/O",
      "AMEND SHARES",
      "AMENDED CHARTER",
      "AN",
      "APPL",
      "ARTICLES OF COR",
      "ASGMT ASSUMED",
      "ASSUME & RELEAS",
      "ASSUME AGRMT",
      "ASSUME/REL/AGT",
      "ASSUMED NAME",
      "BY LAWS",
      "CAN INCORPORATI",
      "CAN PARTNERSHIP",
      "CANCEL ASSUMED",
      "CANCEL NAME",
      "CANCEL PTNRSHP",
      "CERT COMP LIQ",
      "CERT COMP LIQUI",
      "CERT CONV",
      "CERT CORP REC",
      "CERT FOR PTN",
      "CERT INC STOCK",
      "CERT OF AUTHORI",
      "CERT OF EXISTEN",
      "CERT OF OWNERSH",
      "CERT RED CAP",
      "CERT WITH",
      "CERT/DESIGNATIO",
      "CERT/NAME CHANG",
      "CH OF ADD",
      "CH OF AGENT",
      "CHANGE",
      "CHANGE R/A & R/",
      "CHANGE R/O OR R",
      "CHANGE RA",
      "CHANGE RA & RO",
      "CHANGE RO",
      "CHANGE RO & RA",
      "CHANGE RO &/OR ",
      "CHANGE RO OR RA",
      "CHARTER DOCUMEN",
      "CHG RO & RA",
      "CLASSIFY SHARES",
      "COM LIQUIDATION",
      "CONS",
      "CONV",
      "COR AMEND ASSUM",
      "COR AMENDMENT N",
      "COR ASSUMED",
      "COR INC",
      "COR REVOKE P/A",
      "CORP NAME",
      "CORR AMEND PTNR",
      "CORR MERGER",
      "CORR PARTNERSHI",
      "CORR REVCA ASSU",
      "DECLARE BYLAWS",
      "DECLARE PTNRSHP",
      "DECLR PTNRSHP",
      "DESIGNATE RO & ",
      "DIS",
      "DISSOLUTION",
      "DISSOLVE ASSUME",
      "FEDERAL CHARTER",
      "FICTITIOUS NAME",
      "INC",
      "INC",
      "LIMITED PTNRSHP",
      "LIQUIDATION",
      "MERGER",
      "MERGER & N/C",
      "MERGER AGRMT",
      "MODIFY ASSUMED",
      "NAME CHANGE",
      "ORG",
      "OWNERSHIP & MER",
      "OWNERSHIP CERT",
      "OWNERSHIP MERGE",
      "PARTNERSHIP",
      "PARTNERSHIP AGR",
      "PARTNERSHIP ASG",
      "PARTNERSHIP N/C",
      "PTNRSHP & ASSUM",
      "PTNRSHP AGRMT",
      "PTNRSHP/ASSUMED",
      "REG",
      "RESIGN",
      "RESIGN RA",
      "RESIGNATION RA",
      "RESOLVE PTNRSHP",
      "RESTATED ASSUME",
      "RESTATED CHAR",
      "RESTATED CHARTE",
      "RESTATED PTNRSH",
      "RESTATEMENT",
      "REVISED ASSUMED",
      "REVISED PTNRSHP",
      "REVOKE ASSUMED",
      "REVOKE DISSOLUT",
      "STATE",
      "SUR CORP FRANCH",
      "SUR CORP RIGHTS",
      "SURR CORP",
      "SUSPEND",
      "SUSPEND/REINSTA",
      "SUSPENSION",
      "TERM ASSUMED",
      "TERM PARTNERSHI",
      "TRANSFER ASSUM",
      "TRANSFER PTNRSH",
      "VOL SUR COR RIG",
      "VOL SUR CORP FR",
      "VOL SURRENDER",
      "W/DRAL PTNR",
      "W/DRAW & TRANSF",
      "W/DRAW ASSUMED",
      "WILL",
      "WITHDRAW MERGER",
      "WITHDRAW PTNRSH"
    ],
    "DEEDS": [
      "AMEND COMB INTR",
      "AMEND DEED",
      "AMEND TIMBER DE",
      "CAN DEED",
      "CEM DEED",
      "COMB DEED",
      "COMB INSTR",
      "COMB INSTR",
      "COMR DEED",
      "CONTRACT FOR DE",
      "CONTRACT QC DEE",
      "CONVEYANCE",
      "COR CEM DEED",
      "COR COMB DEED",
      "COR COMB INSTR",
      "COR DEED",
      "COR QC DEED",
      "COR SHERIFFS DE",
      "CORR COMR DEED",
      "CORR DEED & AGR",
      "CORR DEED/OPTIO",
      "CORR DEED/RELEA",
      "CORR QC CEM DEE",
      "DEED",
      "DEED & AGRMT",
      "DEED & ASGMT",
      "DEED & ASGMT R/",
      "DEED & LEASE",
      "DEED & NOTICE",
      "DEED & OPTION",
      "DEED & ORDER",
      "DEED & P OF A",
      "DEED & RELEASE",
      "DEED & RW",
      "DEED & TRUST AG",
      "DEED DIRECTION",
      "DEED IMPROVEMEN",
      "DEED OF COVENAN",
      "DEED REFERENCE",
      "DEED REST",
      "DEED/BILL OF SA",
      "DEED/LEASE/OPTI",
      "DEED/SECURE DEB",
      "QC CEM DEED",
      "QC DEED",
      "QC DEED & AGRMT",
      "QC DEED & ASGMT",
      "QC DEED & JDGMT",
      "QC DEED & NOTIC",
      "QC DEED & ORDER",
      "QC DEED & RELEA",
      "QC DEED/REL/P O",
      "REPLACEMENT DEE",
      "REVOKE DEED",
      "SHER DEED",
      "SUBORD DEED",
      "SUPPLE TRUST DE",
      "TERM TIMBER DEE",
      "TIMBER DEED",
      "TRUST DEED",
      "VOID DEED",
      "VOIDED DEED"
    ],
    "DEED OF TRUST": [
      "ADDENDUM D OF T",
      "AGRMT AMEND D/T",
      "AMEND CAN D OF ",
      "AMEND D OF T",
      "AMEND D/T & SUB",
      "AMEND DT & AGT",
      "AMEND DT & ASG",
      "AMEND DT & REL",
      "AMEND DT AGRMT",
      "AMEND MODIFY AG",
      "AMEND MODIFY D/",
      "AMEND SUPPLE D/",
      "AMEND/SUPPLE D/",
      "ASSUMP D OF T",
      "BLANKET TRUST M",
      "CLARIFY D OF T",
      "COMB D OF T",
      "CONFIRM D OF T",
      "COR AMEND DT",
      "COR DT",
      "COR DT & AGRMT",
      "COR DT & ASGMT",
      "COR MOD DT",
      "COR MODIFY D OF",
      "COR MTG",
      "COR SUPPLE DT",
      "CORR AMEND DT/A",
      "CORR DT/AGRT/AS",
      "CORR DT/ASGMT/A",
      "D/T & ASGMT & A",
      "D/T ASGMT & AGR",
      "D/T ASSUMP AGRM",
      "DT",
      "DT & AGRMT",
      "DT & AGRMT & UC",
      "DT & ASGMT",
      "DT MOD AGRMT",
      "DT/AGRMT & ASGM",
      "DT/AGRMT/ASGMT",
      "DT/AGRMT/UCC",
      "DT/ASGMT/AGRMT",
      "DT/ASGMT/AGRT/U",
      "DT/ASGMT/SA/FIN",
      "EXT DT",
      "MEMO AMEND DT",
      "MOD DT",
      "MOD MTG",
      "MOD/SUBORD D OF",
      "MOD/SUPPLE DT",
      "MODIFY/AMEND D/",
      "MODIY D OF T",
      "MORTGAGE & AGRM",
      "MORTGAGE AGRMT",
      "MORTGAGE/D OF T",
      "MTG",
      "MTG & AGRMT",
      "MTG SUBORD",
      "MTG/DT/AGRMT/UC",
      "NOTICE MORTGAGE",
      "REINSTATE DT",
      "REINSTATE MTG",
      "RESTATED MORTGA",
      "SUBORD AMEND D/",
      "SUBORD D OF T",
      "SUBORD MORTGAGE",
      "SUBORD/AMEND DT",
      "SUP DT",
      "SUP DT & MOD",
      "SUPPLE MORTGAGE",
      "TRANSFER DT",
      "VOID CAN D/T",
      "VOID CANCEL D O"
    ],
    "FORECLOSURE": [
      "AMEND FCL",
      "COR FCL",
      "FCL",
      "FORECLOSURE SAL",
      "ORDER FORECLOSU",
      "WDRAL FORECLOSU"
    ],
    "MAPS": [
      "1ST AMEND CONDO",
      "ADOPTION OF PLA",
      "AMEND CONDO",
      "AMEND DECLR CON",
      "CONDO",
      "COR AMEND CONDO",
      "COR CONDO",
      "COR DECLR CONDO",
      "COR PLAT",
      "CORR CONDOMINIU",
      "DECLR CONDO",
      "HWYDOT",
      "PLAT",
      "RATIFY PLAT",
      "ROAD",
      "ROADWAY CORRIDO",
      "SP PLAT",
      "TERM DECLR COND",
      "TERM OF CONDO"
    ],
    "MISCELLANEOUS": [
      "1ST REFUSAL",
      "1ST REFUSAL & C",
      "21ST SUPPLE",
      "29TH SUPPLE",
      "30TH SUPPLE",
      "31ST SUPPLE",
      "32ND SUPPLE",
      "33RD SUPPLE",
      "34TH SUPPLE",
      "35TH SUPPLE",
      "36TH SUPPLE",
      "37TH SUPPLE",
      "38TH SUPPLE",
      "39TH SUPPLE",
      "3RD PT PLEDGE",
      "40TH SUPPLE",
      "41ST SUPPLE",
      "42ND SUPPLE",
      "43RD SUPPLE",
      "44TH SUPPLE",
      "45TH SUPPLE",
      "46TH SUPPLE",
      "47TH SUPPLE",
      "48TH SUPPLE",
      "49TH SUPPLE",
      "50TH SUPPLE",
      "51ST SUPPLE",
      "52ND SUPPLE",
      "53RD SUPPLE",
      "54TH SUPPLE",
      "55TH SUPPLE",
      "56TH SUPPLE",
      "57TH SUPPLE",
      "58TH SUPPLE",
      "59TH SUPPLE",
      "60TH SUPPLE",
      "61ST SUPPLE",
      "62ND SUPPLE",
      "63RD SUPPLE",
      "64TH SUPPLE",
      "65TH SUPPLE",
      "66TH SUPPLE",
      "67TH SUPPLE",
      "68TH SUPPLE",
      "69TH SUPPLE",
      "6TH SUPPLE",
      "70TH SUPPLE",
      "71ST SUPPLE",
      "72ND SUPPLE",
      "73RD SUPPLE",
      "74TH SUPPLE",
      "75TH SUPPLE",
      "76TH SUPPLE",
      "77TH SUPPLE",
      "78TH SUPPLE",
      "79TH SUPPLE",
      "80TH SUPPLE",
      "81ST SUPPLE",
      "82ND SUPPLE",
      "83RD SUPPLE",
      "ABSTRACT/TRUST",
      "ACC/USE AGT",
      "ACCEPT OF SERVI",
      "ACCEPTANCE/TRUS",
      "ACKGT",
      "ACKNOW TERM R/W",
      "ACKNOWLEDGMENT",
      "ADDEN",
      "ADDEN AGRMT",
      "ADDENDUM LEASE",
      "ADDENDUM TO NOT",
      "AFFIDAVIT/TRUST",
      "AFFT",
      "AGMT/AGMT/ASSUM",
      "AGRMT",
      "AGRMT  & ASGMT",
      "AGRMT & AMEND",
      "AGRMT & CONTR",
      "AGRMT & DECLAR",
      "AGRMT & MOD",
      "AGRMT & OPTION",
      "AGRMT & QC DEED",
      "AGRMT & RELEASE",
      "AGRMT & SUBORD",
      "AGRMT & TRUST",
      "AGRMT & WAIVER",
      "AGRMT AMEND",
      "AGRMT MODIFY",
      "AGRMT OF AMEND",
      "AGRMT OF TRANSF",
      "AGRMT RAT",
      "AGT/ASSUMPT/MOD",
      "AMEND & AGRMT",
      "AMEND & ASGMT",
      "AMEND & MOD DT",
      "AMEND & REDUCTI",
      "AMEND & RESTATE",
      "AMEND & SUPPLE",
      "AMEND AGRMT",
      "AMEND AGRMT & R",
      "AMEND AGRMT/ASG",
      "AMEND APPMT TR",
      "AMEND ASGMT",
      "AMEND ASGMT LEA",
      "AMEND CONT",
      "AMEND D OF S",
      "AMEND DECLAR R/",
      "AMEND DETEN AGR",
      "AMEND INSTR",
      "AMEND JDMGT",
      "AMEND LEASE",
      "AMEND LEASE AGT",
      "AMEND LICENSE",
      "AMEND MEMO ACTI",
      "AMEND MEMO LES",
      "AMEND NOTE",
      "AMEND NOTICE",
      "AMEND OPTION",
      "AMEND ORDER",
      "AMEND PETITION",
      "AMEND PLAN DEV",
      "AMEND POND AGT",
      "AMEND PTNRS AGR",
      "AMEND RW AGRMT",
      "AMEND SUB TR",
      "AMEND SUBORD",
      "AMEND TRUST",
      "AMEND WAIVER",
      "AMEND/ASSUMP AG",
      "AMEND/RESTATE",
      "ANNEX",
      "APMT SUB TR/SAT",
      "APPMT",
      "APPMT & ACCEPT",
      "APPMT & OATH",
      "APPMT AGENT",
      "APPMT SUB TR",
      "APPMT TR",
      "APPMT TR/RECONV",
      "APPROVAL OF SAL",
      "APPROVAL/PLANS",
      "APPT SUB TR",
      "ART OF ASSOC",
      "ASSUM/REL/MOD A",
      "ASSUMP",
      "ASSUMP & RAT",
      "ASSUMP & REL",
      "ASSUMP AGRMT",
      "ASSUMP AGRMT/RE",
      "ASSUMP CONSENT",
      "ASSUMP/MOD",
      "ASSUMP/MOD AGRM",
      "ASSUMP/MOD/EXT",
      "ASSUMP/RAT",
      "ASSUMP/SUB AGT",
      "AUTH",
      "BANKRUPTCY",
      "BILL OF SALE",
      "BILL OF SALE/AG",
      "BLDG PLAN APPRO",
      "BOND",
      "BOND & MORTGAGE",
      "CAN ORD",
      "CAN RIGHT REF",
      "CERT",
      "CERT APPMT TR",
      "CERT ASSUPTION",
      "CERT DELEGATION",
      "CERT DISSOLUTIO",
      "CERT OF TR",
      "CERT OF TRAN",
      "CERT OF TRUST",
      "CERT RESOLUTION",
      "CERT/REDEMPTION",
      "CERTIF",
      "CHANGE OF ADDRE",
      "CLAIM LIEN",
      "CLOSURE NOTICE",
      "CODICIL",
      "COMMISSION AGRM",
      "COMMITMENT",
      "COMPLAINT",
      "COMR REPORT",
      "CONFIRM AGRMT",
      "CONSENT & D OF ",
      "CONSENT AGRMT",
      "CONSENT CORR D/",
      "CONSENT ESTOPPE",
      "CONSENT MODIFY",
      "CONSENT SUBORD",
      "CONSENT TO CORR",
      "CONSENT TO LEAS",
      "CONSENT TRANSFE",
      "CONSIGNMENT AGR",
      "CONSOLIDATION",
      "CONST",
      "CONST & AGRMT",
      "CONST & ASSUMP",
      "CONST & MOD",
      "CONST & REL",
      "CONST & SUBORD",
      "CONST & WAIVER",
      "CONT",
      "CONTRACT & AGRM",
      "CONTRACT & ASGM",
      "CONTRACT & D OF",
      "CONTRACT & LEAS",
      "CONTRACT & R OF",
      "CONTRACT AGRMT",
      "CONTRACT TRUST",
      "COR",
      "COR AGRMT",
      "COR AMEND LEASE",
      "COR APPT SUB TR",
      "COR ASSUMP AGT",
      "COR DS",
      "COR DT/ASGT/AGR",
      "COR ESTOP/MOD",
      "COR IND HIST",
      "COR INSTR",
      "COR JDGMT",
      "COR JDGMT & DEE",
      "COR JURY SEL",
      "COR LEASE",
      "COR LEASE AGT",
      "COR MEMO",
      "COR MEMO LEASE",
      "COR MEMO SUBLEA",
      "COR MOD AGT",
      "COR NOTICE",
      "COR NOTICE SUB ",
      "COR ORDER",
      "COR PLAN DEV",
      "COR PROOF SERVI",
      "COR RES",
      "COR RIGHT REFUS",
      "COR SATIS OF IN",
      "COR SUBORD",
      "COR SUBORD AGRM",
      "COR SUBORDINATI",
      "COR SUPPLE",
      "COR TERM AGRMT",
      "COR WAIVER",
      "COR/COMB INSTR",
      "COR/DT/ASGT/AGR",
      "CORP RES",
      "CORR & QC DEED",
      "CORR ADDENDUM",
      "CORR AMEND",
      "CORR AMEND AGRM",
      "CORR AMEND ASGM",
      "CORR ASGMT",
      "CORR COMR REPOR",
      "CORR CONTRACT",
      "CORR DISCLAIMER",
      "CORR LEASE D/T",
      "CORR LEASE/OPTI",
      "CORR MEMO/ACTIO",
      "CORR MOD & ESTO",
      "CORR OATH & APP",
      "CORR OPTION",
      "CORR OPTION AGR",
      "CORR RETENT AGR",
      "CORR REVOKE TRU",
      "CORR SEC AGRMT",
      "CORR SUBLEASE",
      "CORR TERM LEASE",
      "CORR TRUST",
      "CORR TRUST AGRM",
      "CORR TRUST INDE",
      "D OF S & CONTRA",
      "D OF S & WAIVER",
      "D/T OR MTG MODI",
      "DEBTORS PETITIO",
      "DECLAR & WAIVER",
      "DECLAR ANNEXATI",
      "DECLAR CROSS R/",
      "DECLAR FRAN AGR",
      "DECLARE OF MERG",
      "DECLR AGRMT",
      "DECLR AGRMT & R",
      "DECLR ANNEX",
      "DECLR R/W AGRMT",
      "DECLR R/W RESTR",
      "DECLR REAL TRUS",
      "DECLR TRUST",
      "DECLR WITHDRAW",
      "DECREE & JDGMT",
      "DECREE FORFEITU",
      "DEDICATION",
      "DEED/SEP",
      "DEF JDGMT",
      "DESIGN AGENT",
      "DESIGNATE COMR",
      "DESIGNATE PTNRS",
      "DESIGNATION",
      "DETENTION AGRMT",
      "DEVELOPMENT PLA",
      "DISCHARGE",
      "DISCLAIMER",
      "DISCLAIMER ASGM",
      "DISCLOSURE",
      "DISSOLVE AGRMT",
      "DISSOLVE PNTSHP",
      "DIVORCE DECREE",
      "DOMESTICATION",
      "DRAINAGE R/W DE",
      "DRIVEWAY AGRMT",
      "DS",
      "DS & AGRMT",
      "DS ADDEN",
      "ENCROACH CONSEN",
      "EST TAX WAIVER",
      "ESTATE AGRMT",
      "ESTOP & MOD",
      "ESTOP AFFT",
      "ESTOP AGRMT",
      "ESTOPPEL & AGRM",
      "ESTOPPEL & MODI",
      "ESTOPPEL CERT",
      "EXCISE TAX REF",
      "EXT LEASE",
      "EXTENSION AGRMT",
      "FAMILY AGRMT",
      "FAMILY TRUST",
      "FENCE AGRMT",
      "FINAL DECREE",
      "FRANCHISE AGRMT",
      "GRANT AGRMT",
      "GRAVE",
      "GUARANTEE",
      "GUARANTY",
      "GUARDIANSHIP",
      "IND AGRMT",
      "INDENTURE",
      "INSTR DIV",
      "IRS RELEASE",
      "JDGMT",
      "JDGMT & CONTRAC",
      "JDGMT & DEED",
      "JDGMT & ORDER",
      "JDGMT FORFET",
      "JDGMT REPORT CO",
      "JDGMT/DEED/ORDE",
      "JOINDER",
      "JOINDER & CONST",
      "JOINDER & SUBOR",
      "JUDICIAL NOTICE",
      "JURY COMM CERT",
      "JURY COMM STMT",
      "JURY SEL",
      "JURY SELECTION",
      "LANDFILL NOTICE",
      "LEASE",
      "LEASE & AGRMT",
      "LEASE & ASGMT",
      "LEASE & CONTRAC",
      "LEASE & D OF T",
      "LEASE & OPTION",
      "LEASE & R/W AGR",
      "LEASE & SUBORD",
      "LEASE & WAIVER",
      "LEASE AGRMT",
      "LEASE AGRMT & D",
      "LEASE AMEND",
      "LEASE CONTRACT",
      "LEASE EXT AGRMT",
      "LEASE MOD",
      "LEASE OPTION",
      "LEASE PURCH AGR",
      "LEASE RELEASE",
      "LEASE RENEWAL",
      "LEASE SUPPLEMEN",
      "LEASE TERM",
      "LEASE TERM AGRM",
      "LEASE TERM EXT",
      "LEASE W/OPTION",
      "LEASE/1ST REFUS",
      "LEASE/AMEND AGR",
      "LEASE/CONSENT/A",
      "LEASEHOLD EST",
      "LICENSE",
      "LICENSE & AMEND",
      "LICENSE & MEMO",
      "LICENSE & OPTIO",
      "LICENSE AGRMT",
      "LIEN",
      "LIEN AFFIDAVIT",
      "LIEN AGRMT",
      "LIEN EXT",
      "LIEN SALE",
      "LIVING TRUST",
      "LIVING WILL",
      "LOAN ASSUMP/AGT",
      "LOAN MODIFY AGR",
      "MARITAL WAIVER",
      "MEMO",
      "MEMO 1ST REFUSA",
      "MEMO ACTION",
      "MEMO AGRMT",
      "MEMO AMEND LE",
      "MEMO ANNEXATION",
      "MEMO CERT TRUST",
      "MEMO CONTRACT",
      "MEMO DECLR TRUS",
      "MEMO DISPUTE",
      "MEMO EXT",
      "MEMO LEASE",
      "MEMO LEASE AGT",
      "MEMO LEASE/OPT",
      "MEMO LICENSE",
      "MEMO NEG PLE",
      "MEMO OF AGRMT",
      "MEMO OF ANNEXAT",
      "MEMO OF INTERES",
      "MEMO OF PTNRSHP",
      "MEMO OPTION",
      "MEMO OPTION AGT",
      "MEMO REVOKE TR",
      "MEMO SUBLEASE",
      "MEMO TERM/LEASE",
      "MEMO TRUST",
      "MEMO TRUST AGRM",
      "MEMO/AMEND LEAS",
      "MEMO/CO TENANCY",
      "MEMO/LEASE TERM",
      "MEMO/REAL EST",
      "MEMO/SITE LICEN",
      "MOD",
      "MOD & EXT",
      "MOD & EXT AGRMT",
      "MOD & REL AGT",
      "MOD & SUBORD",
      "MOD AGRMT",
      "MOD AGRMT/RELEA",
      "MOD AGRMT/SUB T",
      "MOD AGRMT/SUBOR",
      "MOD DS",
      "MOD DT/ASGT/AGR",
      "MOD LEASE AGT",
      "MOD PLAN DEV",
      "MOD/ASSUMP AGT",
      "MOD/DT/ASGMT/AG",
      "MOD/SUBORD",
      "MODIFY & AGRMT",
      "MODIFY & AMEND",
      "MODIFY & ASSUME",
      "MODIFY & CONSEN",
      "MODIFY & ESTOPP",
      "MODIFY & EXT",
      "MODIFY & RELEAS",
      "MODIFY & SUBORD",
      "MODIFY & WAIVER",
      "MODIFY AGMRT",
      "MODIFY AGRMT",
      "MODIFY AGRMT/ET",
      "MODIFY CONTRACT",
      "MODIFY LEASE",
      "MODIFY LEASE AG",
      "MODIFY NOTE/LIE",
      "MODIFY OPTION",
      "MODIFY SEC AGRM",
      "MODIFY/AMEND",
      "MODIFY/APT SUB ",
      "MODIFY/COR D OF",
      "MODIFY/SUB TR",
      "MODIFY/SUBORD",
      "MOTION",
      "MOTION & ORDER",
      "MV",
      "NO BUILD EASEME",
      "NO LIEN AFFIDAV",
      "NOTE MODIFICATI",
      "NOTICE",
      "NOTICE & AGRMT",
      "NOTICE & APPT",
      "NOTICE & CONTRA",
      "NOTICE & LEASE",
      "NOTICE & OPTION",
      "NOTICE & ORDER",
      "NOTICE & TRUST",
      "NOTICE LEASE",
      "NOTICE LIEN",
      "NOTICE LIEN CLA",
      "NOTICE OF AGRMT",
      "NOTICE OF BNKCY",
      "NOTICE OF CANCE",
      "NOTICE OF CONSE",
      "NOTICE OF DEFAU",
      "NOTICE OF SUB T",
      "NOTICE SUB TR",
      "NOTICE/CONTRACT",
      "NOTICE/CONVERSI",
      "NOTICE/TRUST",
      "NT",
      "OATH & APPMT",
      "OATH OF OFFICE",
      "OFFER & CONTRAC",
      "OFFER/PER",
      "OFFICIAL BOND",
      "OPERATING AGRMT",
      "OPINION & ORDER",
      "OPT/1ST REF",
      "OPTION",
      "OPTION & AGRMT",
      "OPTION & LEASE",
      "OPTION & NOTICE",
      "OPTION & OFFER",
      "OPTION & SUBORD",
      "OPTION AGRMT",
      "OPTION CONTRACT",
      "OPTION EXTENSIO",
      "OPTION RELEASE",
      "OPTION/PURCHASE",
      "ORD",
      "ORDER",
      "ORDER & JDGMT",
      "ORDER & NOTICE",
      "ORDER & REPORT",
      "ORDER N/C",
      "ORDER/CAN D OF ",
      "ORDER/DISCHARGE",
      "ORDER/FORFEITUR",
      "OWN NOTICE",
      "PARKING AGRMT",
      "PART TERM LEASE",
      "PAYMENT BOND",
      "PER BOND",
      "PERMIT",
      "PET",
      "PLAN DEV",
      "PLEDGE/SEC AGRM",
      "POND AGRMT",
      "POSTPONEMENT LI",
      "POWER OF AUTH",
      "PRELIM INJUNCTI",
      "PROM NOTE",
      "PROOF OF SERVIC",
      "PROP AGRMT",
      "PROP DIV AGRMT",
      "PROP RESOLUTION",
      "PROP SETTLEMENT",
      "PT TERM OF LEAS",
      "PTNR RESOLUTION",
      "PTNRSHP AFFIDAV",
      "PURCHASE & LEAS",
      "PURCHASE AGRMT",
      "PURCHASE OPTION",
      "PURCHASE/CONTRA",
      "QC",
      "QC AGRMT",
      "QC LEASE",
      "R OF D DISCLAIM",
      "R OF W TERM AGR",
      "R/W & ABANDONME",
      "R/W & RESTRICTI",
      "R/W & SUBORD AG",
      "R/W AGRMT & DCL",
      "RAT",
      "RAT & RES",
      "RE-RECORDING",
      "REASGMT LEASE",
      "REASSIGN LEASE",
      "REC",
      "REC OF SAT",
      "RECEIPT",
      "RECEIVERSHIP",
      "RECISSION",
      "RECISSION OF D/",
      "RECITALS",
      "RECOMB INSTR",
      "RECON",
      "REDUCT OF CAPIT",
      "REFORM INSTR",
      "REFUSAL OPTION",
      "REINSTATE",
      "REINSTATE TRUST",
      "REL COMMON LIEN",
      "RENEWAL OF LEAS",
      "RENEWAL OPTION",
      "RENUN",
      "RENUN APPMT TR",
      "REP",
      "REPORT",
      "REPORT & ORDER",
      "REPORT OF COMRS",
      "REPORT OF JUROR",
      "REPURCHASE OPTI",
      "RES",
      "RES NOTICE",
      "RES OF SAT",
      "RESCIND D OF S",
      "RESD APPROVAL",
      "RESIGN & APPMT",
      "RESIGN AGENT",
      "RESIGN SUB TR",
      "RESIGN TR",
      "RESIGN/APPMT TR",
      "RESOLUTION",
      "RESTATE SUBORD",
      "RESTATED LEASE",
      "RETENTION AGRMT",
      "REV LICENSE",
      "REV TRUST",
      "REVOKE & DECLR",
      "REVOKE ADDENDUM",
      "REVOKE AFFIDAVI",
      "REVOKE AGRMT",
      "REVOKE AMEND",
      "REVOKE ATTACHME",
      "REVOKE CERTIFIC",
      "REVOKE CODICIL",
      "REVOKE CONTRACT",
      "REVOKE D OF S",
      "REVOKE DECLR",
      "REVOKE OPTION",
      "REVOKE R/W ETAL",
      "REVOKE REFUSAL",
      "REVOKE REL",
      "REVOKE TR",
      "RIDER",
      "RIDER REVOCATIO",
      "RIGHT 1ST REF",
      "RO",
      "ROAD AGRMT",
      "ROAD MAINTENANC",
      "RULES/REGULATIO",
      "RW COV",
      "SAFISFAC JDGMT",
      "SALE & ASGMT",
      "SEC AGRMT",
      "SEP DECREE",
      "SEPTIC TANK NOT",
      "SERVICE AGRMT",
      "SETTLEMENT",
      "SETTLEMENT AGRM",
      "SHERIFFS BILL",
      "SIGN LEASE",
      "SLOPE AGRMT",
      "SPREADER AGRMT",
      "SPT TK/LIMITATI",
      "SPT TK/SUITABLE",
      "STATE AUTHORITY",
      "STATEMENT",
      "STIPULATION",
      "SUB COLL",
      "SUB LAND D OF T",
      "SUB LEASE",
      "SUB NEW LAND D/",
      "SUB OF COLLATER",
      "SUB SECURITY D/",
      "SUB TR & AMEND ",
      "SUB TR & CAN D/",
      "SUB TR & REL",
      "SUB TR & SATISF",
      "SUB TR & SUBORD",
      "SUB TR AGRMT",
      "SUB TR/CAN D OF",
      "SUB TR/RECONVEY",
      "SUB TR/SATIS IN",
      "SUB TRUST AGRMT",
      "SUB TRUST TR",
      "SUBDIV DEDICATI",
      "SUBLEASE",
      "SUBLEASE AGRMT",
      "SUBORD",
      "SUBORD & AGRMT",
      "SUBORD & CONSEN",
      "SUBORD & ESTOP",
      "SUBORD & MODIFY",
      "SUBORD AGRMT",
      "SUBORD JDGMT",
      "SUBORD JDGMT LI",
      "SUBORD LEASE",
      "SUBORD LIEN",
      "SUBORD OPTION",
      "SUBORD TAX LIEN",
      "SUBORD/MOD AGRM",
      "SUBORD/RW/AMEND",
      "SUBORD/SUB TR",
      "SUBORDINATION",
      "SUBROGATION AGR",
      "SUBROGATION/JDG",
      "SUM OF TRUST",
      "SUP & AMEND CON",
      "SUP AGRMT",
      "SUP DECLR",
      "SUP JDGMT",
      "SUP LEASE",
      "SUP MEMO/ACTION",
      "SUP MTG/SEC AGR",
      "SUPP LEASE & D/",
      "SUPP MEMO ACTIO",
      "SUPP TR INDENTU",
      "SUPPL MEMO/ACTI",
      "SUPPLE & AMEND",
      "SUPPLE DECLAR R",
      "SUPPLE DECLAR T",
      "SUPPLE R/W AGRM",
      "SUPPLE TO LEASE",
      "SUPPLEMENT INST",
      "SURRENDER LEASE",
      "TAX LIEN",
      "TEMP CONSTR R/W",
      "TEMP CONTR R OF",
      "TERM & LEASE",
      "TERM/WAIVER AGR",
      "TIMBER AGRMT",
      "TIMBER SALE AGR",
      "TOWN BOUNDARIES",
      "TR RELEASE AGRM",
      "TRAFFIC ANALYSI",
      "TRANSFER",
      "TRANSFER LEASE",
      "TRANSFER LIEN",
      "TRANSFER NOTES",
      "TRANSFER OF NOT",
      "TRANSFER RIGHT",
      "TRIPARTITE AGRM",
      "TRUST",
      "TRUST AGRMT",
      "TRUST AGRMT & M",
      "TRUST AGRT SUPP",
      "TRUST INDENTURE",
      "TRUST INSTR",
      "TRUST NOTICE",
      "TRUSTEES CERT",
      "UNIFIED DEV PLA",
      "UNTITLED DOC",
      "USE RESTRICTION",
      "UTILITY AGRMT",
      "UTILITY R OF W",
      "UTILITY R/W AGR",
      "VAC/RESCISSION",
      "VARIANCE",
      "VERIFICATION",
      "VOL PETITION",
      "W/DRAL NOTICE",
      "WAIVE 1ST REFUS",
      "WAIVE AGRMT",
      "WAIVE AMEND AGR",
      "WAIVER",
      "WAIVER & AGRMT",
      "WAIVER & AMEND",
      "WAIVER & CONST",
      "WAIVER & REL",
      "WAIVER & TERM",
      "WAIVER 1ST REF",
      "WAIVER AGRMT",
      "WAIVER OF LIEN",
      "WAIVER OF OPTIO",
      "WAIVER OF RIGHT",
      "WAIVER/AGRMT",
      "WAIVER/MODIFY",
      "WAIVER/REL OPT",
      "WAIVER/VARIANCE",
      "WAIVERS & AGRMT",
      "WETLANDS NOTICE",
      "WILL & TESTAMEN",
      "WITHDRAW",
      "WITHDRAW D OF S",
      "WRAP-AROUND AGR"
    ],
    "NOTARY": [
      "COR NOTARY",
      "NOTARY",
      "REINSTATE NOTAR",
      "RESIGN NOTARY",
      "REST NOTARY",
      "REVOKE NOTARY",
      "SUSPEND NOTARY"
    ],
    "POWER OF ATTORNEY": [
      "ACCEPT APPMT",
      "ACCEPTS P OF A",
      "AMEND P OF A",
      "CAN P OF A",
      "CONSENT REVOKE ",
      "COR P OF A",
      "CORR REVOKE P O",
      "INSTRUCT P OF A",
      "MOD P OF A",
      "NOTICE & P OF A",
      "NOTICE REVOKE P",
      "NOTICE SUB P OF",
      "P OF A",
      "P OF A & AGRMT",
      "P OF A & ASGMT",
      "P OF A & DECLR",
      "P OF A & PTNRSH",
      "P OF A ADDEN",
      "POA",
      "RESIGN & P OF A",
      "RESIGN P OF A",
      "REVISED P OF A",
      "REVOKE & P OF A",
      "REVOKE P OF A",
      "SUB P OF A",
      "SUP P OF A",
      "TERM P OF A"
    ],
    "RELEASE": [
      "ABAN & REL",
      "AGRMT OF RELEAS",
      "COR REL",
      "COR REL DEED",
      "CORR RELEASE & ",
      "MODIFY/RELEASE",
      "P/REL",
      "P/REL",
      "P/SAT",
      "PT RELEASE JDGM",
      "PT RELEASE LIEN",
      "REL",
      "REL & ASSUMPTIO",
      "REL 1ST REF",
      "REL 1ST REFUSAL",
      "REL AGRMT",
      "REL ASGMT",
      "REL CLAIMS",
      "REL D/T & ASGMT",
      "REL DECLR TRUST",
      "REL DEED",
      "REL DEED & AGRM",
      "REL DEED & ASGM",
      "REL DT",
      "REL JDGMT",
      "REL JDGMT LIEN",
      "REL LEASE ASGMT",
      "REL LIEN",
      "REL MECHANIC LI",
      "REL NOTICE",
      "REL OPTION",
      "REL OPTION AGRM",
      "REL OPTION/OFFE",
      "REL RIGHTS",
      "REL TIMBER DEED",
      "REL TRUST DEED",
      "REL/ASGMT/P OF ",
      "RELEASE & AGRMT",
      "RELEASE & AMEND",
      "RELEASE & APPMT",
      "RELEASE & ASGMT",
      "RELEASE & CONSE",
      "RELEASE & QC DE",
      "RELEASE & QC R/",
      "RELEASE & SUBOR",
      "RELEASE & WAIVE",
      "RELEASE AUTHORI",
      "RELEASE BOND",
      "RELEASE CONTRAC",
      "RELEASE DT/ASGM",
      "RELEASE INTERES",
      "RELEASE LEASE",
      "RELEASE LIFE ES",
      "RELEASE LTD APP",
      "RELEASE MORTGAG",
      "RELEASE MTG/ASG",
      "RELEASE OF TERM",
      "RELEASE QC DEED",
      "RELEASE R/W AGR",
      "RELEASE RIDER",
      "RELEASE TAX LIE",
      "RELEASE/MORTGAG",
      "RELEASE/RECONVE",
      "RELEASE/TERM R/",
      "RELEASING JDGMT",
      "RESCIND RELEASE",
      "SUB TR/REL DEED",
      "TERM/RELEASE R/"
    ],
    "RESTRICTVE COVENANTS": [
      "ADDN COV",
      "AGRMT & RESTR C",
      "AGRMT OF RESTRI",
      "AMEND COV",
      "AMEND DECLR",
      "AMEND RESTRICTI",
      "ANNEX COV",
      "ASGMT COVENANTS",
      "CAN RES COVENAN",
      "COMPLY RESTR CO",
      "CONSENT AMEND C",
      "CONSENT COVENAN",
      "COR AMEND BY LA",
      "COR AMEND COV",
      "COR COV",
      "COR DECLR",
      "COR DEED RES",
      "COR REV COVENAN",
      "COR SUPP COV",
      "COR TRUST/COVNA",
      "CORR COVENENT",
      "CORR DECLARATIO",
      "COV VARIANCE",
      "COVENANT & SUBO",
      "COVENANT AGRMT",
      "DECLR",
      "DECLR COV",
      "DECLR COVTS/ANN",
      "DESIGN COVENANT",
      "EXTEND COVENANT",
      "JOINDER COVENAN",
      "MOD COV",
      "PROTECT COV",
      "PROTECT COVENAN",
      "REL COV",
      "REMOVE COVENANT",
      "RES COV",
      "REST",
      "REST COV",
      "RESTATE COVENAN",
      "RESTRICT AGRMT",
      "RESTRICT COVENA",
      "RESTRICTIONS AG",
      "REVISED COVENAN",
      "REVOKE & COVENA",
      "REVOKE COVENANT",
      "SUB REST COVENA",
      "SUBORD COVENANT",
      "SUP COV",
      "SUP DECLR COV",
      "SUPPLE RESTR CO",
      "TERM COVENANTS",
      "TERM PT COV",
      "TRUST/COVENANTS",
      "W/DRAL COV",
      "W/DRAW DECLR",
      "WAIVE COV",
      "WAIVE RESTRICTI"
    ],
    "RIGHT OF WAY": [
      "ABAN RW",
      "AGRMT & RW",
      "AMEND DECLR R O",
      "AMEND RW",
      "ASGMT R OF W",
      "CAN D/T & R OF ",
      "CONST R OF W DE",
      "CONST RW",
      "COR AMEND RW",
      "COR DECLR RW",
      "COR MOD RW",
      "COR REL RW",
      "COR RW",
      "COR RW AGRMT",
      "COR RW DEED",
      "DECLR RW",
      "DECLR RW/AGRMT",
      "DECLR TERM R OF",
      "DEDICATION R OF",
      "LEASE & R OF W",
      "MEMO OF R OF W",
      "MOD DECLR RW",
      "MOD RW",
      "MOD RW AGRMT",
      "NOTICE & R OF W",
      "PARKING RW",
      "QC DEED R OF W",
      "QC R OF W",
      "QC RW DEED",
      "R OF W",
      "R OF W & AGRMT",
      "R OF W & CONSEN",
      "R OF W & COVENA",
      "R OF W & RELEAS",
      "R OF W & RESTRI",
      "R OF W & SUBORD",
      "R OF W & WAIVER",
      "R OF W GRANT",
      "R OF W NOTICE",
      "R OF W WAIVER",
      "RECIPROCAL R OF",
      "RECONVEY R OF W",
      "REL & QC R OF W",
      "REL RW",
      "REL RW AGRMT",
      "RELEASE R OF W",
      "RELOCATE RW",
      "RESTRICT & R OF",
      "RW",
      "RW",
      "RW & AGRMT",
      "RW & ASGMT",
      "RW AGRMT",
      "RW DEED",
      "RW LICENSE",
      "RW REL",
      "SUBORD R OF W",
      "SUP RW",
      "SUP RW AGRMT",
      "TEMP R OF W DEE",
      "TERM CROSS R OF",
      "TERM DECLR R OF",
      "W/DRAW RW",
      "WAIVER R OF W",
      "WITHDRAW R OF W"
    ],
    "SATISFACTION": [
      "CAN AGRMT & CON",
      "CAN AMEND & D/T",
      "CAN AMEND ASGMT",
      "CAN ASSUMP AGRM",
      "CAN COMB D OF T",
      "CAN CORR D/T",
      "CAN D/T",
      "CAN D/T & AGRMT",
      "CAN D/T & AMEND",
      "CAN D/T & ASGMT",
      "CAN D/T & ASSUM",
      "CAN D/T & MOD D",
      "CAN D/T & SUBOR",
      "CAN DECLARATION",
      "CAN DEED RESTRI",
      "CAN DT/ASGMT/AG",
      "CAN ESTP & MODI",
      "CAN LEASE",
      "CAN LEASE & AGR",
      "CAN LEASE & D/T",
      "CAN LEASE AGRMT",
      "CAN LEASE ASGMT",
      "CAN LEASE MEMO",
      "CAN LEASE/R OF ",
      "CAN LIEN",
      "CAN LIS PENDENS",
      "CAN LTD WARRANT",
      "CAN MEMO",
      "CAN MOD AGRMT",
      "CAN MODIFY AGRM",
      "CAN MODIFY D OF",
      "CAN MODIFY/WAIV",
      "CAN MTG",
      "CAN NOTICE",
      "CAN OPTION",
      "CAN RELEASE AGR",
      "CAN RW",
      "CAN SPT TK NOTI",
      "CAN SUBORD",
      "CAN SUBORD AGRM",
      "CAN SUBORD/AMEN",
      "CAN SUBORDINATI",
      "CAN SUPPLE D OF",
      "CAN TRUST DEED",
      "CAN/AMEND/MOD D",
      "CANCEL",
      "CANCEL & AGRMT",
      "CANCEL & AMEND",
      "CANCEL & ASGMT",
      "CANCEL & RELEAS",
      "CANCEL AGRMT",
      "CANCEL AGRMT/AS",
      "CANCEL AMEND",
      "CANCEL AMEND AS",
      "CANCEL AMEND D/",
      "CANCEL AMENDMEN",
      "CANCEL ASGMT",
      "CANCEL CONTRACT",
      "CANCEL CORR D/T",
      "CANCEL D OF S",
      "CANCEL D OF T",
      "CANCEL D/T & AM",
      "CANCEL D/T ETAL",
      "CANCEL DT & ASG",
      "CANCEL JDGMT",
      "CANCEL ORDER",
      "CANCEL SUPPLE D",
      "CANCEL TAX LIEN",
      "CANCEL TERM ASG",
      "COR SAT",
      "CORR CAN D/T & ",
      "CORR CAN LEASE",
      "CORR CAN MTG",
      "CORR CANCEL D/T",
      "CORR CANCEL LEA",
      "CORR CANCEL MTG",
      "CORR VOID CAN D",
      "ORDER OF CANCEL",
      "SAT",
      "SAT OF INSTR",
      "SATFAC & REL AS",
      "SATIFAC OF INST",
      "SATISFAC AGRMT",
      "SATISFAC OF ASG",
      "SATISFAC OF INS",
      "SATISFAC/RELEAS",
      "SATISFY MORTGAG",
      "SATSIFACTION",
      "TERM & CANCEL",
      "TERM & RELEASE",
      "TERM 1ST REF",
      "TERM ADVANCES",
      "TERM AGRMT",
      "TERM AGRMT & DE",
      "TERM ASGMT",
      "TERM ASGMT & LE",
      "TERM CONTRACT",
      "TERM DISCLOSURE",
      "TERM LEASE",
      "TERM LEASE & RE",
      "TERM LEASE AGRM",
      "TERM MEMO LEASE",
      "TERM NOTICE",
      "TERM OF ADVANCE",
      "TERM OF AGRMT",
      "TERM OF CONTRAC",
      "TERM OF LEASE",
      "TERM OPTION",
      "TERM OPTION AGT",
      "TERM OPTIONAL",
      "TERM RESTRICTIO",
      "TERM RW",
      "TERM RW AGRMT",
      "TERM RW DEED",
      "TERM TRUST",
      "TERM/ABANDONMEN",
      "TERM/OFFER AGRM",
      "TERM/RELEASE",
      "TERMINATION",
      "TERMINATION AGR",
      "VOID CONTRACT",
      "VOID SAT"
    ],
    "UCC": [
      "CANCEL UCC",
      "COR UCC",
      "U C C",
      "UCC"
    ]
  };

export default class CivilProducer extends AbstractProducer {
    browser: puppeteer.Browser | undefined;
    browserPages = {
        generalInfoPage: undefined as undefined | puppeteer.Page
    };
    urls = {
        generalInfoPage: 'https://rdlxweb.guilfordcountync.gov/guilfordNameSearch.php'
    }

    xpaths = {
        isPAloaded: '//input[@id="Accept"]'
    }

    constructor(publicRecordProducer: IPublicRecordProducer) {
        // @ts-ignore
        super();
        this.publicRecordProducer = publicRecordProducer;
        this.stateToCrawl = this.publicRecordProducer?.state || '';
    }

    async init(): Promise<boolean> {
        this.browser = await this.launchBrowser();
        this.browserPages.generalInfoPage = await this.browser.newPage();
        await this.setParamsForPage(this.browserPages.generalInfoPage);
        try {
            this.browserPages.generalInfoPage?.setDefaultTimeout(100000);
            await this.browserPages.generalInfoPage.goto(this.urls.generalInfoPage, { waitUntil: 'load' });
            return true;
        } catch (err) {
            console.warn(err);
            return false;
        }
    }

    async read(): Promise<boolean> {
        try {
            await this.browserPages.generalInfoPage?.waitForXPath(this.xpaths.isPAloaded);
            return true;
        } catch (err) {
            console.warn('Problem loading civil producer page.');
            return false;
        }
    }

    // To check empty or space
    isEmptyOrSpaces(str: string) {
        return str === null || str.match(/^\s*$/) !== null;
    }

    getDateStringDDMMYY(date: Date): string {
        return ("00" + date.getDate()).slice(-2) + "/" + ("00" + (date.getMonth() + 1)).slice(-2) + "/" + date.getFullYear();
    }

    async getData(page: puppeteer.Page, date: any, name: any, docType: any): Promise<any> {
        const parseName: any = this.newParseName(name.trim())
        if (parseName?.type && parseName?.type == 'COMPANY') return false;
        let practiceType = this.getPracticeType(docType)
        const productName = `/${this.publicRecordProducer.state.toLowerCase()}/${this.publicRecordProducer.county}/${practiceType}`;
        const prod = await db.models.Product.findOne({name: productName}).exec();
        const data = {
            'Property State': 'NC',
            'County': 'Guilford',
            'First Name': parseName.firstName,
            'Last Name': parseName.lastName,
            'Middle Name': parseName.middleName,
            'Name Suffix': parseName.suffix,
            'Full Name': parseName.fullName,
            "vacancyProcessed": false,
            fillingDate: date,
            productId: prod._id,
            originalDocType: docType
        };
        return await this.civilAndLienSaveToNewSchema(data);
    }

    // This is main function
    async parseAndSave(): Promise<boolean> {
        let countRecords = 0;
        let page = this.browserPages.generalInfoPage!;
        try{
            const civilUrl: string = 'https://rdlxweb.guilfordcountync.gov/guilfordNameSearch.php';
            let dateRange = await this.getDateRange('North Carolina', 'Guilford');
            let fromDate = dateRange.from;
            let toDate = dateRange.to;
            await Promise.all([
                page.click('#Accept'),
                page.waitForNavigation()
            ])
            let tryCount = 0;
            while (fromDate <= toDate) {
                if (tryCount > 5){
                    break;
                }
                try{
                    let dateStringDay = this.getFormattedDate(new Date(fromDate));
                    console.log(dateStringDay);
                    await page.goto(civilUrl, { waitUntil: 'networkidle0' });
                    let grantorButton = await page.$x('//input[@value="Grantor"]');
                    await grantorButton[0].click();
                    await page.click('#start_date', {clickCount: 3, delay: 200});
                    await page.type('#start_date', dateStringDay, {delay: 500});
                    await page.click('#end_date', {clickCount: 3, delay: 200});
                    await page.type('#end_date', dateStringDay, {delay: 500});
                    let searchButton = await page.$x('//input[@value="Search"]');
                    await Promise.all([
                        searchButton[0].click(),
                        page.waitForNavigation()
                    ]);
                    let resultRows = await page.$x('//tr[@bgcolor="#FFFFFF"]');
                    console.log(resultRows.length);
                    if (resultRows.length < 2){
                        fromDate.setDate(fromDate.getDate() + 1);
                        await this.randomSleepIn5Sec();
                        tryCount = 0;
                        continue;
                    }
                    let checkAllButton = await page.$x('//input[@onclick="CheckAll()"]');
                    await checkAllButton[0].click();
                    await Promise.all([
                        page.click('#displaybutton'),
                        page.waitForNavigation()
                    ]);
                    let grantorNames = await page.$x('//a[contains(@href, "guilfordDetailScreen.php")]/ancestor::tr/td[5]');
                    let docTypes = await page.$x('//a[contains(@href, "guilfordDetailScreen.php")]/ancestor::tr/td[3]');
                    let dateRecordings = await page.$x('//a[contains(@href, "guilfordDetailScreen.php")]/ancestor::tr/td[1]');
                    for (let i = 1; i < grantorNames.length; i++) {
                        let grantorName = await grantorNames[i].evaluate(el => el.textContent?.trim());
                        let docType = await docTypes[i].evaluate(el => el.textContent?.trim());
                        let dateRecording = await dateRecordings[i].evaluate(el => el.textContent?.trim());
                        for(const docTypeObj in docTypeObjs){
                            let found = false;
                            for(const docTypeStr of docTypeObjs[docTypeObj]){
                                if(docTypeStr == docType){
                                    docType = docTypeObj + " - " + docType;
                                    found = true;
                                    break;
                                }
                            }
                            if(found){
                                break;
                            }
                        }
                        console.log(grantorName, docType, dateRecording);
                        if(await this.getData(page, dateRecording, grantorName, docType)){
                            countRecords += 1;
                        }
                    }
                    fromDate.setDate(fromDate.getDate() + 1);
                    await this.randomSleepIn5Sec();
                    tryCount = 0;
                } catch(e){
                    console.log(e);
                    tryCount += 1;
                    await this.randomSleepIn5Sec();
                }
            }
            console.log(countRecords);
            await AbstractProducer.sendMessage('North Carolina', 'Guilford', countRecords, 'Civil');
            return true;
        } catch (error){
            console.log(error);
            const errorImage = await this.uploadImageOnS3(page);
            await AbstractProducer.sendMessage('North Carolina', 'Guilford', countRecords, 'Civil', errorImage);
            return false;
        }
    }
}