extend type Query {
    fetchOwnerProductProperties(token: String!, from: String!, to: String!,perPage: Int, currentPage: Int, practiceType: [String], filters: String, count: Int!, state: String, county: String, zip: String, owners: String): OwnerProductProperty
}

type OwnerProductProperty {
    success: Boolean!
    data: String
    count: Int
    error: String
}
